### ISSUE TITLE
Feature suggestion: Yarn install

### ISSUE THREAD

**Issue by mike3run** [delfrrr/npm-consider#1]
Some teams use yarn instead of npm maybe with some flag the command can be yarn add instead of npm save?

**Comment by delfrrr** [comment]
Thank you for the feedback!

Do you have an idea for intuitive argument syntax in mind?

Also, as far as I know, yarn has a different algorithm for flattering dependencies and some similar functionality like `yarn licenses` and `yarn why`. Not sure if yarn support fits this tool, or it is an idea for another tool 😉

**Comment by mike3run** [comment]
the licenses part is amazing here and yarn why is also i think a different story

I'm thinking something more along the lines of passing some flags so instead of `--save` we can use `-y` and for yarn dev `-yd` maybe?

Like really all the package could work the same just use those install commands optionally without needing to make a duplicate one (?)

**Comment by delfrrr** [comment]
Well, support `yarn add` must be easy. Calculate impact based on their algorithm can take some time.
Looks like a nice opportunity for me to look into `yarn` source 😃

**Comment by Ghostium** [comment]
Maybe you could calculate the license summary based on the installed packages in node_modules. Then you would be independent of the package manager used.

**Comment by delfrrr** [comment]
@Ghostium unfortunately, node_modules may contain redundant packages

**Comment by delfrrr** [comment]
Added support of `yarn add` https://github.com/delfrrr/npm-consider/releases/tag/v1.2.0
