### ISSUE TITLE
Feature request: GitHub support

### ISSUE THREAD

**Issue by larsgw** [delfrrr/npm-consider#7]
Feature request: support for GitHub-based dependencies.

**Comment by delfrrr** [comment]
I'd love to add `git` dependencies from the very beginning but it will mean the downloading of whole package via `git`; right now tool fetches only headers from the `npm`

Do you know any solution how can I get information about dependencies and size without downloading the whole git repo?

**Comment by larsgw** [comment]
The GitHub API has license information ([example](https://api.github.com/repos/larsgw/citation.js)); I don't know about git repos in general, didn't think of that.

**Comment by delfrrr** [comment]
Ok. I'm working on implementation of GitHub support via API. It's gonna be ready soon.
@larsgw will you be able to test it from the feature brunch?

**Comment by larsgw** [comment]
Will do, thanks in advance. I don't see the branch yet, is that correct?

**Comment by delfrrr** [comment]
@larsgw just committed

**Comment by larsgw** [comment]
The GitHub dependency I have has the GitHub-specific syntax described in https://docs.npmjs.com/files/package.json#github-urls (but with the now-default `github:` prefix), so that doesn't work yet.

**Comment by delfrrr** [comment]
@larsgw fixed

**Comment by larsgw** [comment]
Works almost I think, but the `#` should be stripped from the hash/ref for the API call.

**Comment by delfrrr** [comment]
@larsgw fixed 😃

**Comment by larsgw** [comment]
Yup, that seems to work. Thanks!

**Comment by delfrrr** [comment]
Released in [v1.7.0](https://github.com/delfrrr/npm-consider/releases/tag/v1.7.0)
